# Form implementation generated from reading ui file 'final_voting_gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(220, 0, 281, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.title_label.setObjectName("title_label")
        self.instruction_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.instruction_label.setGeometry(QtCore.QRect(200, 90, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.instruction_label.setFont(font)
        self.instruction_label.setObjectName("instruction_label")
        self.voter_id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.voter_id_input.setGeometry(QtCore.QRect(70, 200, 113, 21))
        self.voter_id_input.setObjectName("voter_id_input")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 200, 51, 16))
        self.label.setObjectName("label")
        self.jane_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jane_radio.setGeometry(QtCore.QRect(320, 200, 89, 20))
        self.jane_radio.setObjectName("jane_radio")
        self.john_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.john_radio.setGeometry(QtCore.QRect(320, 250, 89, 20))
        self.john_radio.setObjectName("john_radio")
        self.jiselle_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jiselle_radio.setGeometry(QtCore.QRect(320, 300, 89, 20))
        self.jiselle_radio.setObjectName("jiselle_radio")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(10, 510, 75, 24))
        self.submit_button.setObjectName("submit_button")
        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(100, 510, 75, 24))
        self.clear_button.setObjectName("clear_button")
        self.results_jane_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.results_jane_label.setGeometry(QtCore.QRect(460, 410, 49, 16))
        self.results_jane_label.setObjectName("results_jane_label")
        self.results_john_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.results_john_label.setGeometry(QtCore.QRect(460, 460, 49, 16))
        self.results_john_label.setObjectName("results_john_label")
        self.results_jiselle_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.results_jiselle_label.setGeometry(QtCore.QRect(460, 510, 49, 16))
        self.results_jiselle_label.setObjectName("results_jiselle_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting System"))
        self.title_label.setText(_translate("MainWindow", "WELCOME TO THE VOTING SYSTEM"))
        self.instruction_label.setText(_translate("MainWindow", "Please enter your voter ID and select a candidate."))
        self.label.setText(_translate("MainWindow", "Voter ID:"))
        self.jane_radio.setText(_translate("MainWindow", "Jane"))
        self.john_radio.setText(_translate("MainWindow", "John"))
        self.jiselle_radio.setText(_translate("MainWindow", "Jiselle"))
        self.submit_button.setText(_translate("MainWindow", "Cast Vote"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.results_jane_label.setText(_translate("MainWindow", "TextLabel"))
        self.results_john_label.setText(_translate("MainWindow", "TextLabel"))
        self.results_jiselle_label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
